swagger: "2.0"
info:
  version: "0.0.1"
  title: Twitter Push App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /twitterfeed/{user}/{message}/:
    # binds a127 app logic to a route
    x-swagger-router-controller: push_twitterfeed
    get:
      description: Returns 'Nothing' to the caller
      # used as the method name of the controller
      operationId: twitterfeed
      parameters:
        - name: user
          in: path
          description: twitter user
          required: true
          type: string
        - name: message
          in: path
          description: twitter message
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/TwitterResponse"
        # responses may: fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  TwitterResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
