apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
  labels:
    component: elk
    role: logstash
spec:
  type: LoadBalancer
  selector:
    component: elk
    role: logstash
  ports:
  - name: log4j
    port: 5000
    protocol: TCP
