apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-webapp-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: java-webapp-demo
    spec:
      containers:
      - name: java-webapp-demo
        image: cvugrinec/java-webapp-demo
        ports:
        - containerPort: 8080
