apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-webapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-webapp
    spec:
      containers:
      - name: redis-webapp
        image: cvugrinec/java-webapp-redisdemo:2.1
        ports:
        - containerPort: 8080
