apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rss-webapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rss-webapp
    spec:
      containers:
      - name: rss-webapp
        image: cvugrinec/rss_bookmarker:1.5
        ports:
        - containerPort: 8080
