apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elk
    role: master
spec:
  selector:
    component: elk
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
