azure_vm { 'chrisba1':
  location                      => 'westeurope',
  image                         => 'canonical:UbuntuServer:16.10:16.10.201701030',
  user                          => 'chris',
  password                      => 'HelloWorld123!',
  size                          => 'Standard_D2_V2',
  resource_group                => 'msbf-demo1',
  storage_account               => 'chrisba1',
  storage_account_type          => 'Standard_GRS',
  os_disk_name                  => 'osdisk01',
  os_disk_caching               => 'ReadWrite',
  os_disk_create_option         => 'fromImage',
  os_disk_vhd_container_name    => 'chrisba1',
  os_disk_vhd_name              => 'chrisba1',
  dns_servers                   => '8.8.8.8 10.1.1.1',
  public_ip_allocation_method   => 'Dynamic',
  public_ip_address_name        => 'chrisba1',
  virtual_network_name          => 'vnet01',
  virtual_network_address_space => '10.0.0.0/16',
  subnet_name                   => 'subnet01',
  subnet_address_prefix         => '10.0.0.0/24',
  ip_configuration_name         => 'ip_config_chrisba1',
  private_ip_allocation_method  => 'Dynamic',
  network_interface_name        => 'nicchrisba1',
  extensions                    => {
    'CustomScriptForLinux' => {
       'auto_upgrade_minor_version' => false,
       'publisher'                  => 'Microsoft.Azure.Extensions',
       'type'                       => 'CustomScript',
       'type_handler_version'       => '2.0',
       'settings'                   => {
         'commandToExecute' => 'curl -k https://raw.githubusercontent.com/chrisvugrinec/ms-buddyfinder/master/01_puppet/provisionscripts/provision-buildagent.sh | sudo bash'
       },
     },
  },
}
